hive> desc dw.fct_event_reg;
OK
terminal_id             int
app_version             string
event_id                int
utm_id                  bigint
site_id                 int
gu_id                   string
session_id              string
event_value             string
ref_page_id             string
ref_page_value          string
ref_site_id             int
user_id                 int
page_id                 int
page_value              string
shop_id                 int
ref_shop_id             int
starttime               bigint
endtime                 bigint
page_level_id           int
location                string
ctag                    string
hot_goods_id            int
rule_id                 string
test_id                 string
select_id               string
page_lvl2_value         string
ref_page_lvl2_value     string
event_lvl2_value        string
jpk                     int
pit_type                int
sortdate                string
sorthour                int
lplid                   int
ptplid                  int
gid                     string
ugroup                  string
date                    string